### ISSUE TITLE
deprecation links

### ISSUE THREAD

**Issue by aryairani** [etaque/elm-dialog#6]
Could you update the deprecation info to describe or list or link to some of the better ways to show dialog modals? etaque/elm-dialog is currently the top Google hit for an autocompleted search "elm modal" -> "elm modal window"

**Comment by etaque** [comment]
Hello,
Good to know, I wasn't aware of this google visibility. I have a better version of the lib, still have to finish documentation, I should be able to publish it at the end of the week, otherwise I'll add recommendations to the readme.

**Comment by aryairani** [comment]
Awesome!

**Comment by etaque** [comment]
README updated with alternatives and WIP.
